[package]
name = "rocket-app-static"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"